sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - vue_master
notifications:
  email: false
before_script:
- npm install
script:
- npm run --silent build
after_success:
- bash deploy.sh
env:
  global:
  - GH_USER: chrisgorgo
  - GH_REPO: arielletambini.github.io
  - secure: SV2nnOpzhbMBRmEwQ2KEv2MatOXdj7LhckPJ7ILSYk8rkYCAt06YBThhfsGsXcEIrkVQx+V04Vg4m3trV5NVFnfKM9otTRdgLvXx0GIN2frTLN/AfLgOUlQh3OPSjWFtlMbz53ewytlyNYMlajnWJhl71x0lGZ8asvTTeSPfZmIv8fNyCnSgU8IbFrrg5TUUFr9oTJO5Ey2J/4RvDaXPieWpTA6ITnVTH2gTN5aTwvjYdmb+EuBE16cgEn0k5/7Bx22EGNANGQISoB6byLFnPFPYQij1fvujSeb8isKzClXAlwX7U2D38KseBCITyvcXr26Z0ENb7unQyuDVDzMkduQ9oAK27JlfXXwk8YAI83ktXaoPCDPpTkI659qSab5VzbOqyDsvFhSJRrZ7vZ7F8xW42btxn8Rg2rGMOkrFtbjaBgXPg0dckA6CvXCJZ8xK9df4IOvQtAhHBP/dGwMrsubx3QN16zTBWr6hwqx+jLwkyRNIIEdayDgETbeBzFIH9y6lsCOlRvCWM/P6upwxFPR1M7XtS2cgXRVgdpzNpdQmPLTbqyD7V7UsyfwL8A0YMMhDTNBdFckYdj69rVmtujJ2VuW4cqGvHkp8aujSjKIssp0JBlOnFw25V4S1uv8gYLyD/Os6vNzxtjbPvurnX6ak4T8wZrEU6zoVyvaDt9c=
  - secure: iOI8uSNNovNlEEiFwmZfDlre5yR7sYF5n/Kgc4TkJLuGWyjVirUNg7BtHoZWpSVWFKEJVU9qF2/PNrTJtMnyGPByM2gx9gk2sgA87BgKVCSRZw1Jbze0zrHNV0hGALSBcvtkILaVxDj//TQUNeKiBVCyulBqH68er01MlA64s/x9zmrcVUanFKsTtwWkeFODXh4ufB7IL686LvOcy4fV2hGpi1k2IPWdH07TPOs9rFvor1eDjXu4J/Ae3wr7pyLQ9x4OYSVtWWQmv4pN8pyuK6zCqu1kyUTBaKw36YR3lbfRk9RwSSb0WqXHFlnr53WOCCRIYGUsrFNHyeCqrJBTaw3H9XaZ8f7OSs6y4M1lCmsyc7ay8s3+uFGIRPl//aly4qjVd64xkfOf99ox7xRvpN4tX1KTpy/K3pdR6JyiyUIrKenMj9GbRFwGc6uq5fl5UvZfzfDePbrVG3cHF1AXtBrXqKIV4VXl0gMU85SlmH0JdIuwJzLvXj7Qy8JYGhFca9dYn4FgnPR4HNQg3w5/hHdMah5c1UhEimCmCJbDBfIYPorGpo19Sk+9YFTbVNSFa+V4JIZKfR/0zefCwaxVAy+hJYLHbGXolQ/N8ubGdDSiwKbzhQfV3UiD3awik2kc1BAWs89x8MpODy/1bFx6pToR1L9ruBh+b7VPkc9vnIs=
