sudo: false
language: node_js
node_js:
- '12.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - vue_master
notifications:
  email: false
before_script:
- npm install
script:
- npm run --silent build
after_success:
- bash deploy.sh
env:
  global:
  - GH_USER: chrisgorgo
  - GH_REPO: arielletambini.github.io